### PR TITLE
Improved syntax highlight

### PR DESCRIPTION
**Pull request by kachurun**
This is a redesigned html.tmLanguage with full support for all HTML tags. I also fixed expression handling in various situations, such as:

```
id="some_{ state.id }"
attr1="number in attribute name"
attr2={ expression }
attr3="{ expressionInQuotes }"
attr4='{ expressionInQuotes }'
```

I also changed the way <script> is handled, now it thinks that the content is of the source.ts type
There are also plans to make a separation by script type, depending on the `lang="ts" / lang="typescript"` and the same for `<style>` (like SCSS/LESS/Stylus style type)

### CODE REVIEW

**Comment by Kal-Aster** [comment]
Hi! Thank you for your work, I really appreciate your effort in making it more readable and explicit about the embedded languages.
However I noticed that it doesn't correctly handle many cases, since riot component are ofter invalid HTML.

Consider the following `test.riot`:
```
<test>
    <component></component>
    <div
        validattr
        nextattrwillbeinvalid="-->"thisshouldbeinvalid="<--"

        thisshouldbeok=ok

        validexpression={ expression() }
        validmixedexpression="test { expression() } test"

        "invalid"
        'invalid'

        "
        '
        =
    ></div>

    <script>
        export default {
            onBeforeMount() {
                console.log("hello");
            },
            expression() {
                return 12;
            }
        }
    </script>
</test>
```

`<test>` should be highlighted as a tag
`<component></component>` also should be highlighted as a tag

`nextattrwillbeinvalid="-->"thisshouldbeinvalid="<--"` should be correctly highlighted until `thisshouldbeinvalid="<--"` because html specification states that attributes should have at least a space before its name (I was actually working on this)

`validexpression={ expression() }` the expression is not properly highlighted
`validmixedexpression="test { expression() } test"` same here

all the following text in the div tag is correctly highlighted as invalid.

`</test>` should be correctly highlighted as closing tag



About the snippet you provided, I currently get valid highlight.



I really like the idea of using embedded language, since it's more explicit and future-proof, but we should cover better these case expecially the riot-specific ones (custom tag names and expressions).

**Comment by kachurun** [comment]
Yes, it also still has problems with some situations like:

```
    <div class="project-card flexbe-white-card shadow large rounded hoverable { clsx({ hover: (state.inHover || state.inDropdown) }) }"
         if={ state.view !== 'table' }
         onmouseenter={ () => cardHover(true) }
<----- Something goes wrong after this line
         onmouseleave={ () => cardHover(false) }
         onpointerdown={ onPointerDown }
         onclick={ goToPages }
    >
```

**Comment by Kal-Aster** [comment]
I actually published an improvement in attribute highlights, however I see that your last snippet is highlighted incorrectly. I'll keep it for testing.

I presume I tested your previous one with the improved syntax highlight that I didn't publish yet...

**Comment by kachurun** [comment]
And this code cause issue as well (with my tmlanguage)
```
<div class="flexbe-action-buttons edit-button">
    <svg />
</div>
```

**Comment by Kal-Aster** [comment]
Yes, I suppose any autoclosing tag that instead should have content. In fact replacing svg with input gives correct highlight

**Comment by kachurun** [comment]
BTW, could you downgrade the VS Code version to "vscode": "^1.82.0"? This version should work with the current version of Cursor IDE, which is based on VS Code 1.93.1 for now.

**Comment by kachurun** [comment]
I also notice wrong comment format in riot template, it appears as `//` instead of `<!-- -->`

**Comment by Kal-Aster** [comment]
> I also notice wrong comment format in riot template, it appears as `//` instead of `<!-- -->`

You mean in your implementation or mine? I get correct comments highlight

**Comment by kachurun** [comment]
In your setup, I rebuilt the version from the upstream/main branch, but it’s acting strange. It might be some kind of cache issue, so I may need to change the version to update it. I’ll try again later

**Pull request closed without merging**
